# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.40.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    ENV["GITLAB_API_HTTPARTY_OPTIONS"]="{verify: false}"
  end

  desc "Test: Clone a repo" 
  lane :clone do
    migrate_git_repository(from_repo_url: "git@gitlab.devsub.net:cocoapods/ivbase64.git", to_repo_url: "git@git.innovaptor.at:mexx/test.git")
  end

  desc "Lists all projects that"
  lane :list_projects do
    projects_src = gitlab_get_projects(endpoint: ENV["FL_GITLAB_ENDPOINT_SRC"], api_token: ENV["FL_GITLAB_TOKEN_SRC"]).sort { |a, b| a.path_with_namespace <=> b.path_with_namespace }
    projects_dst = gitlab_get_projects(endpoint: ENV["FL_GITLAB_ENDPOINT_DST"], api_token: ENV["FL_GITLAB_TOKEN_DST"]).sort { |a, b| a.path_with_namespace <=> b.path_with_namespace }

    Helper.log.info "#{projects_src.count} projects Projecst read from the source"
    Helper.log.info "#{projects_dst.count} projects Projecst read from the destination"

    project_paths_dst = projects_dst.map { |p| p.path }

    projects_not_migrated = projects_src.select { |p| !project_paths_dst.include? p.path }
    projects_already_migrated = projects_src.select { |p| project_paths_dst.include? p.path }

    if projects_not_migrated.empty?
      puts "All projects have already been migrated"
    else
      puts "These project are not yet migrated:"
      projects_not_migrated.each do |p| 
        puts "\t⚠️  #{p.path_with_namespace}"
      end
    end

    if projects_already_migrated.empty? 
      puts "No projecst migrated yet"
    else
      puts "These project have already been migrated:"
      projects_already_migrated.each do |p|
        puts "\t✅  #{p.path_with_namespace}"
      end
    end 
  end

  desc "Migrate a specific project"
  desc "Specify the project that should be migrated by its path (with namespace) via the project parameter"
  desc "Example: fastlane migrate project:cocoapods/specs"
  lane :migrate do |params|
    project_path = params[:project] || prompt(text: "Please enter the path (including the namespace) of the project you want to migrate")
    projects_src = gitlab_get_projects(endpoint: ENV["FL_GITLAB_ENDPOINT_SRC"], api_token: ENV["FL_GITLAB_TOKEN_SRC"]).select { |p| p.path_with_namespace == project_path }

    Helper.log.info("Checking the source for existing project #{project_path}")
    raise "Project with path #{project_path} not found in source #{ENV["FL_GITLAB_ENDPOINT_SRC"]}" unless projects_src.count == 1
    project = projects_src.first
    Helper.log.info("Checking the destination for existing project #{project_path}")
    projects_dst = gitlab_get_projects(endpoint: ENV["FL_GITLAB_ENDPOINT_DST"], api_token: ENV["FL_GITLAB_TOKEN_DST"]).select { |p| p.path_with_namespace == project_path }
    raise "Project with path #{project_path} already exists in destination #{ENV["FL_GITLAB_ENDPOINT_DST"]}" unless projects_dst.empty?

    Helper.log.info("Checks OK, Starting to migrate project #{project_path} to #{ENV['FL_GITLAB_ENDPOINT_DST']}")
    gitlab_create_project(
      endpoint_src: ENV["FL_GITLAB_ENDPOINT_SRC"], 
      api_token_src: ENV["FL_GITLAB_TOKEN_SRC"], 
      endpoint_dst: ENV["FL_GITLAB_ENDPOINT_DST"], 
      api_token_dst: ENV["FL_GITLAB_TOKEN_DST"], 
      project: project
    )

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
